version: 0.2
run-as: root

phases:

 install:
  commands:
    - echo Installing app dependencies...
     
     
 pre_build:
   commands:
     - echo Logging in to Amazon EKS...

     - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
     - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

 build: # Build Docker image and tag it with the commit sha
  commands:
    - echo Build started on `date`
    - echo Building the Docker image...
   # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
    - docker images
    #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
   # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG bjnandi/test:$IMAGE_TAG
    - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
    - docker images
    - docker ps
    - docker run -itd -p 80:80 --name $IMAGE_REPO_NAME $IMAGE_REPO_NAME 
    - pwd
    - docker ps
    
    - docker exec -it $IMAGE_REPO_NAME sh
    - cd /
    - cd /var/www/html
    
    - ls -la
    - php artisan test
    - php artisan test --testsuite=Unit --stop-on-failure
    
    

 post_build: # Push the Docker image to the ECR
  commands:
   - echo Build completed on `date`
   - echo Pushing the Docker image...
  # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  # - docker push bjnandi/test:latest
