version: 0.2
run-as: root

phases:

 install:
  commands:
    - echo Installing app dependencies...
     
     
 pre_build:
   commands:
     - echo Logging in to Amazon EKS...

     - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
     - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

 build: # Build Docker image and tag it with the commit sha
  commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker-composer build
    - dokcer images
    - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 
    - docker run -itd -p 80:80 $IMAGE_REPO_NAME $IMAGE_REPO_NAME:$IMAGE_TAG 
    
    - docker exec  $IMAGE_REPO_NAME ls -la
    - docker exec  $IMAGE_REPO_NAME php artisan test
    - docker exec  $IMAGE_REPO_NAME php artisan test --testsuite=Unit --stop-on-failure

 post_build: # Push the Docker image to the ECR
  commands:
   - echo Build completed on `date`
   - echo Pushing the Docker image...
